[package]
name = "borrow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "one"
path = "src/main1.rs"

[[bin]]
name = "two"
path = "src/main2.rs"